/*American Express*/


package com.core_scorecard.core_scorecard.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.util.HashMap;
import java.util.Map;
import java.util.Collections;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;

import com.wavemaker.runtime.data.model.CustomQuery;
import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.exception.QueryParameterMismatchException;

@Service
public class Core_scorecardQueryExecutorServiceImpl implements Core_scorecardQueryExecutorService {
	private static final Logger LOGGER = LoggerFactory.getLogger(Core_scorecardQueryExecutorServiceImpl.class);

	@Autowired
	@Qualifier("core_scorecardWMQueryExecutor")
	private WMQueryExecutor queryExecutor;

	@Transactional(value = "core_scorecardTransactionManager")
	@Override
	public Page<Object> executeGetEmpByLTA(Pageable pageable)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        return queryExecutor.executeNamedQuery("getEmpByLTA", params, pageable);
	}
	@Transactional(value = "core_scorecardTransactionManager")
	@Override
	public Page<Object> executeGetEmpByPFA(Pageable pageable)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        return queryExecutor.executeNamedQuery("getEmpByPFA", params, pageable);
	}
	@Transactional(value = "core_scorecardTransactionManager")
	@Override
	public Page<Object> executeGetPlatform(Pageable pageable)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        return queryExecutor.executeNamedQuery("getPlatform", params, pageable);
	}
	@Transactional(value = "core_scorecardTransactionManager")
	@Override
	public Page<Object> executeGetApplication(Pageable pageable, java.lang.String aim)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("aim", aim);
        return queryExecutor.executeNamedQuery("getApplication", params, pageable);
	}

	@Transactional(value = "core_scorecardTransactionManager")
	@Override
	public Page<Object> executeWMCustomQuerySelect(CustomQuery query, Pageable pageable) {
	    return queryExecutor.executeCustomQuery(query, pageable);
	}

	@Transactional(value = "core_scorecardTransactionManager")
    @Override
    public int executeWMCustomQueryUpdate(CustomQuery query) {
        return queryExecutor.executeCustomQueryForUpdate(query);
    }
}

