/*American Express*/


package com.core_scorecard.core_scorecard.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.model.CustomQuery;
import com.wavemaker.runtime.data.exception.QueryParameterMismatchException;

public interface Core_scorecardQueryExecutorService {
    Page<Object> executeGetEmpByLTA(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeGetEmpByPFA(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeGetPlatform(Pageable pageable) throws QueryParameterMismatchException;

	
	Page<Object> executeWMCustomQuerySelect(CustomQuery query, Pageable pageable) ;

	int executeWMCustomQueryUpdate(CustomQuery query) ;
}

