/*American Express*/

package com.core_scorecard.core_scorecard.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.core_scorecard.core_scorecard.*;

/**
 * Service object for domain model class Platform.
 * @see com.core_scorecard.core_scorecard.Platform
 */

public interface PlatformService {
   /**
	 * Creates a new platform.
	 * 
	 * @param created
	 *            The information of the created platform.
	 * @return The created platform.
	 */
	public Platform create(Platform created);

	/**
	 * Deletes a platform.
	 * 
	 * @param platformId
	 *            The id of the deleted platform.
	 * @return The deleted platform.
	 * @throws EntityNotFoundException
	 *             if no platform is found with the given id.
	 */
	public Platform delete(Integer platformId) throws EntityNotFoundException;

	/**
	 * Finds all platforms.
	 * 
	 * @return A list of platforms.
	 */
	public Page<Platform> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<Platform> findAll(Pageable pageable);
	
	/**
	 * Finds platform by id.
	 * 
	 * @param id
	 *            The id of the wanted platform.
	 * @return The found platform. If no platform is found, this method returns
	 *         null.
	 */
	public Platform findById(Integer id) throws EntityNotFoundException;
	/**
	 * Updates the information of a platform.
	 * 
	 * @param updated
	 *            The information of the updated platform.
	 * @return The updated platform.
	 * @throws EntityNotFoundException
	 *             if no platform is found with given id.
	 */
	public Platform update(Platform updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the platforms in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the platform.
	 */

	public long countAll();


    public Page<Platform> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

