/*American Express*/

package com.core_scorecard.core_scorecard.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.*;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.core_scorecard.core_scorecard.*;


/**
 * ServiceImpl object for domain model class VAimOwner.
 * @see com.core_scorecard.core_scorecard.VAimOwner
 */
@Service("core_scorecard.VAimOwnerService")
public class VAimOwnerServiceImpl implements VAimOwnerService {


    private static final Logger LOGGER = LoggerFactory.getLogger(VAimOwnerServiceImpl.class);

    @Autowired
    @Qualifier("core_scorecard.VAimOwnerDao")
    private WMGenericDao<VAimOwner, VAimOwnerId> wmGenericDao;
    public void setWMGenericDao(WMGenericDao<VAimOwner, VAimOwnerId> wmGenericDao){
        this.wmGenericDao = wmGenericDao;
    }
     @Transactional(readOnly = true, value = "core_scorecardTransactionManager")
     public Page<VAimOwner> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable){
          LOGGER.debug("Fetching all associated");
          return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
     }

    @Transactional(value = "core_scorecardTransactionManager")
    @Override
    public VAimOwner create(VAimOwner vaimowner) {
        LOGGER.debug("Creating a new vaimowner with information: {}" , vaimowner);
        return this.wmGenericDao.create(vaimowner);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "core_scorecardTransactionManager")
    @Override
    public VAimOwner delete(VAimOwnerId vaimownerId) throws EntityNotFoundException {
        LOGGER.debug("Deleting vaimowner with id: {}" , vaimownerId);
        VAimOwner deleted = this.wmGenericDao.findById(vaimownerId);
        if (deleted == null) {
            LOGGER.debug("No vaimowner found with id: {}" , vaimownerId);
            throw new EntityNotFoundException(String.valueOf(vaimownerId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(readOnly = true, value = "core_scorecardTransactionManager")
    @Override
    public Page<VAimOwner> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all vaimowners");
        return this.wmGenericDao.search(queryFilters, pageable);
    }
    
    @Transactional(readOnly = true, value = "core_scorecardTransactionManager")
    @Override
    public Page<VAimOwner> findAll(Pageable pageable) {
        LOGGER.debug("Finding all vaimowners");
        return this.wmGenericDao.search(null, pageable);
    }

    @Transactional(readOnly = true, value = "core_scorecardTransactionManager")
    @Override
    public VAimOwner findById(VAimOwnerId id) throws EntityNotFoundException {
        LOGGER.debug("Finding vaimowner by id: {}" , id);
        VAimOwner vaimowner=this.wmGenericDao.findById(id);
        if(vaimowner==null){
            LOGGER.debug("No vaimowner found with id: {}" , id);
            throw new EntityNotFoundException(String.valueOf(id));
        }
        return vaimowner;
    }
    @Transactional(rollbackFor = EntityNotFoundException.class, value = "core_scorecardTransactionManager")
    @Override
    public VAimOwner update(VAimOwner updated) throws EntityNotFoundException {
        LOGGER.debug("Updating vaimowner with information: {}" , updated);
        this.wmGenericDao.update(updated);
        return this.wmGenericDao.findById((VAimOwnerId)updated.getId());
    }

    @Transactional(readOnly = true, value = "core_scorecardTransactionManager")
    @Override
    public long countAll() {
        return this.wmGenericDao.count();
    }
}


