/*American Express*/

package com.core_scorecard.core_scorecard.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.core_scorecard.core_scorecard.*;

/**
 * Service object for domain model class VAimOwner.
 * @see com.core_scorecard.core_scorecard.VAimOwner
 */

public interface VAimOwnerService {
   /**
	 * Creates a new vaimowner.
	 * 
	 * @param created
	 *            The information of the created vaimowner.
	 * @return The created vaimowner.
	 */
	public VAimOwner create(VAimOwner created);

	/**
	 * Deletes a vaimowner.
	 * 
	 * @param vaimownerId
	 *            The id of the deleted vaimowner.
	 * @return The deleted vaimowner.
	 * @throws EntityNotFoundException
	 *             if no vaimowner is found with the given id.
	 */
	public VAimOwner delete(VAimOwnerId vaimownerId) throws EntityNotFoundException;

	/**
	 * Finds all vaimowners.
	 * 
	 * @return A list of vaimowners.
	 */
	public Page<VAimOwner> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<VAimOwner> findAll(Pageable pageable);
	
	/**
	 * Finds vaimowner by id.
	 * 
	 * @param id
	 *            The id of the wanted vaimowner.
	 * @return The found vaimowner. If no vaimowner is found, this method returns
	 *         null.
	 */
	public VAimOwner findById(VAimOwnerId id) throws EntityNotFoundException;
	/**
	 * Updates the information of a vaimowner.
	 * 
	 * @param updated
	 *            The information of the updated vaimowner.
	 * @return The updated vaimowner.
	 * @throws EntityNotFoundException
	 *             if no vaimowner is found with given id.
	 */
	public VAimOwner update(VAimOwner updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the vaimowners in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the vaimowner.
	 */

	public long countAll();


    public Page<VAimOwner> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

