/*American Express*/

package com.core_scorecard.core_scorecard;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Column;
import javax.persistence.Embeddable;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;




/**
 * VAimOwnerId generated by hbm2java
 */
@Embeddable
public class VAimOwnerId  implements java.io.Serializable
 {


private String applicationName;
private String applicationId;
private String applicationDirector;
private String applicationIntegrator;
private String applicationPfa;
private String applicationVpLevel1;
private String applicationVpLevel1CostCenter;
private String applicationVpLevel2;
private String applicationSvp;
private String productionSupportDirector;
private String productionSupportVp;
private String owningBusinessDirector;
private String owningBusinessVp;
private String lineOfBusinessLvl1;
private String lineOfBusinessLvl2;

    public VAimOwnerId() {
    }




    

    @Column(name="application_name")
    public String getApplicationName() {
        return this.applicationName;
    }
    
    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName;
    }

    

    @Column(name="application_id")
    public String getApplicationId() {
        return this.applicationId;
    }
    
    public void setApplicationId(String applicationId) {
        this.applicationId = applicationId;
    }

    

    @Column(name="application_director")
    public String getApplicationDirector() {
        return this.applicationDirector;
    }
    
    public void setApplicationDirector(String applicationDirector) {
        this.applicationDirector = applicationDirector;
    }

    

    @Column(name="application_integrator")
    public String getApplicationIntegrator() {
        return this.applicationIntegrator;
    }
    
    public void setApplicationIntegrator(String applicationIntegrator) {
        this.applicationIntegrator = applicationIntegrator;
    }

    

    @Column(name="application_pfa")
    public String getApplicationPfa() {
        return this.applicationPfa;
    }
    
    public void setApplicationPfa(String applicationPfa) {
        this.applicationPfa = applicationPfa;
    }

    

    @Column(name="application_vp_level1")
    public String getApplicationVpLevel1() {
        return this.applicationVpLevel1;
    }
    
    public void setApplicationVpLevel1(String applicationVpLevel1) {
        this.applicationVpLevel1 = applicationVpLevel1;
    }

    

    @Column(name="application_vp_level1_cost_center")
    public String getApplicationVpLevel1CostCenter() {
        return this.applicationVpLevel1CostCenter;
    }
    
    public void setApplicationVpLevel1CostCenter(String applicationVpLevel1CostCenter) {
        this.applicationVpLevel1CostCenter = applicationVpLevel1CostCenter;
    }

    

    @Column(name="application_vp_level2")
    public String getApplicationVpLevel2() {
        return this.applicationVpLevel2;
    }
    
    public void setApplicationVpLevel2(String applicationVpLevel2) {
        this.applicationVpLevel2 = applicationVpLevel2;
    }

    

    @Column(name="application_svp")
    public String getApplicationSvp() {
        return this.applicationSvp;
    }
    
    public void setApplicationSvp(String applicationSvp) {
        this.applicationSvp = applicationSvp;
    }

    

    @Column(name="production_support_director")
    public String getProductionSupportDirector() {
        return this.productionSupportDirector;
    }
    
    public void setProductionSupportDirector(String productionSupportDirector) {
        this.productionSupportDirector = productionSupportDirector;
    }

    

    @Column(name="production_support_vp")
    public String getProductionSupportVp() {
        return this.productionSupportVp;
    }
    
    public void setProductionSupportVp(String productionSupportVp) {
        this.productionSupportVp = productionSupportVp;
    }

    

    @Column(name="owning_business_director")
    public String getOwningBusinessDirector() {
        return this.owningBusinessDirector;
    }
    
    public void setOwningBusinessDirector(String owningBusinessDirector) {
        this.owningBusinessDirector = owningBusinessDirector;
    }

    

    @Column(name="owning_business_vp")
    public String getOwningBusinessVp() {
        return this.owningBusinessVp;
    }
    
    public void setOwningBusinessVp(String owningBusinessVp) {
        this.owningBusinessVp = owningBusinessVp;
    }

    

    @Column(name="line_of_business_lvl1")
    public String getLineOfBusinessLvl1() {
        return this.lineOfBusinessLvl1;
    }
    
    public void setLineOfBusinessLvl1(String lineOfBusinessLvl1) {
        this.lineOfBusinessLvl1 = lineOfBusinessLvl1;
    }

    

    @Column(name="line_of_business_lvl2")
    public String getLineOfBusinessLvl2() {
        return this.lineOfBusinessLvl2;
    }
    
    public void setLineOfBusinessLvl2(String lineOfBusinessLvl2) {
        this.lineOfBusinessLvl2 = lineOfBusinessLvl2;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof VAimOwnerId) )
		 return false;

		 VAimOwnerId that = ( VAimOwnerId ) o;

         return ( (this.getApplicationName()==that.getApplicationName()) || ( this.getApplicationName()!=null && that.getApplicationName()!=null && this.getApplicationName().equals(that.getApplicationName()) ) )
 && ( (this.getApplicationId()==that.getApplicationId()) || ( this.getApplicationId()!=null && that.getApplicationId()!=null && this.getApplicationId().equals(that.getApplicationId()) ) )
 && ( (this.getApplicationDirector()==that.getApplicationDirector()) || ( this.getApplicationDirector()!=null && that.getApplicationDirector()!=null && this.getApplicationDirector().equals(that.getApplicationDirector()) ) )
 && ( (this.getApplicationIntegrator()==that.getApplicationIntegrator()) || ( this.getApplicationIntegrator()!=null && that.getApplicationIntegrator()!=null && this.getApplicationIntegrator().equals(that.getApplicationIntegrator()) ) )
 && ( (this.getApplicationPfa()==that.getApplicationPfa()) || ( this.getApplicationPfa()!=null && that.getApplicationPfa()!=null && this.getApplicationPfa().equals(that.getApplicationPfa()) ) )
 && ( (this.getApplicationVpLevel1()==that.getApplicationVpLevel1()) || ( this.getApplicationVpLevel1()!=null && that.getApplicationVpLevel1()!=null && this.getApplicationVpLevel1().equals(that.getApplicationVpLevel1()) ) )
 && ( (this.getApplicationVpLevel1CostCenter()==that.getApplicationVpLevel1CostCenter()) || ( this.getApplicationVpLevel1CostCenter()!=null && that.getApplicationVpLevel1CostCenter()!=null && this.getApplicationVpLevel1CostCenter().equals(that.getApplicationVpLevel1CostCenter()) ) )
 && ( (this.getApplicationVpLevel2()==that.getApplicationVpLevel2()) || ( this.getApplicationVpLevel2()!=null && that.getApplicationVpLevel2()!=null && this.getApplicationVpLevel2().equals(that.getApplicationVpLevel2()) ) )
 && ( (this.getApplicationSvp()==that.getApplicationSvp()) || ( this.getApplicationSvp()!=null && that.getApplicationSvp()!=null && this.getApplicationSvp().equals(that.getApplicationSvp()) ) )
 && ( (this.getProductionSupportDirector()==that.getProductionSupportDirector()) || ( this.getProductionSupportDirector()!=null && that.getProductionSupportDirector()!=null && this.getProductionSupportDirector().equals(that.getProductionSupportDirector()) ) )
 && ( (this.getProductionSupportVp()==that.getProductionSupportVp()) || ( this.getProductionSupportVp()!=null && that.getProductionSupportVp()!=null && this.getProductionSupportVp().equals(that.getProductionSupportVp()) ) )
 && ( (this.getOwningBusinessDirector()==that.getOwningBusinessDirector()) || ( this.getOwningBusinessDirector()!=null && that.getOwningBusinessDirector()!=null && this.getOwningBusinessDirector().equals(that.getOwningBusinessDirector()) ) )
 && ( (this.getOwningBusinessVp()==that.getOwningBusinessVp()) || ( this.getOwningBusinessVp()!=null && that.getOwningBusinessVp()!=null && this.getOwningBusinessVp().equals(that.getOwningBusinessVp()) ) )
 && ( (this.getLineOfBusinessLvl1()==that.getLineOfBusinessLvl1()) || ( this.getLineOfBusinessLvl1()!=null && that.getLineOfBusinessLvl1()!=null && this.getLineOfBusinessLvl1().equals(that.getLineOfBusinessLvl1()) ) )
 && ( (this.getLineOfBusinessLvl2()==that.getLineOfBusinessLvl2()) || ( this.getLineOfBusinessLvl2()!=null && that.getLineOfBusinessLvl2()!=null && this.getLineOfBusinessLvl2().equals(that.getLineOfBusinessLvl2()) ) );

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getApplicationName() == null ? 0 : this.getApplicationName().hashCode() );
         result = 37 * result + ( getApplicationId() == null ? 0 : this.getApplicationId().hashCode() );
         result = 37 * result + ( getApplicationDirector() == null ? 0 : this.getApplicationDirector().hashCode() );
         result = 37 * result + ( getApplicationIntegrator() == null ? 0 : this.getApplicationIntegrator().hashCode() );
         result = 37 * result + ( getApplicationPfa() == null ? 0 : this.getApplicationPfa().hashCode() );
         result = 37 * result + ( getApplicationVpLevel1() == null ? 0 : this.getApplicationVpLevel1().hashCode() );
         result = 37 * result + ( getApplicationVpLevel1CostCenter() == null ? 0 : this.getApplicationVpLevel1CostCenter().hashCode() );
         result = 37 * result + ( getApplicationVpLevel2() == null ? 0 : this.getApplicationVpLevel2().hashCode() );
         result = 37 * result + ( getApplicationSvp() == null ? 0 : this.getApplicationSvp().hashCode() );
         result = 37 * result + ( getProductionSupportDirector() == null ? 0 : this.getProductionSupportDirector().hashCode() );
         result = 37 * result + ( getProductionSupportVp() == null ? 0 : this.getProductionSupportVp().hashCode() );
         result = 37 * result + ( getOwningBusinessDirector() == null ? 0 : this.getOwningBusinessDirector().hashCode() );
         result = 37 * result + ( getOwningBusinessVp() == null ? 0 : this.getOwningBusinessVp().hashCode() );
         result = 37 * result + ( getLineOfBusinessLvl1() == null ? 0 : this.getLineOfBusinessLvl1().hashCode() );
         result = 37 * result + ( getLineOfBusinessLvl2() == null ? 0 : this.getLineOfBusinessLvl2().hashCode() );

         return result;
     }


}

